version: "3.7"
services:
  elasticsearch:
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    ports:
      - 9200:9200

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:7.7.1
    container_name: kibana
    ports:
      - 5601:5601