spring:
  elasticsearch:
    rest:
      uris: ${ELASTIC_URIS:http://localhost:9200}
      username: ${ELASTIC_USERNAME:}
      password: ${ELASTIC_PASSWORD:}
      read-timeout: ${ELASTIC_READ_TIMEOUT:30s}
      connection-timeout: ${ELASTIC_READ_TIMEOUT:3s}
    info:
      template-name: arah
      template-pattern: arah-*
      index-name: arah-articles
      mapping: classpath:mapping/article.json

server:
  port: ${APP_PORT:8080}

application:
  clean-install: ${CLEAN_INSTALL_ENABLED:false}