spring:
  elasticsearch:
    rest:
      uris: ${ELASTIC_URIS}
      username: ${ELASTIC_USERNAME}
      password: ${ELASTIC_PASSWORD}
      read-timeout: ${ELASTIC_READ_TIMEOUT}
      connection-timeout: ${ELASTIC_READ_TIMEOUT}
    info:
      template-name: arah
      template-pattern: arah-*
      index-name: arah-articles
      mapping: classpath:mapping/article.json
      rating-script: "if (doc['score'].value == 0.0F || doc['votes'].value == 0L) { return 0.0F; } else { return (doc['score'].value / doc['votes'].value); }"
      rating-script-name: calculate-rating

server:
  port: ${APP_PORT}

application:
  clean-install: ${CLEAN_INSTALL_ENABLED}